language: node_js
node_js:
  - 12
git:
  depth: 3
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://pekuria.github.io/myexquisitewear-app/
deploy:
  provider: s3
  access_key_id: AKIA4ERDOQJ6PJYID56J
  secret_access_key:
    secure: P9UfCNwkW2z5j9kFZhvAz0wlea3pqPxvdoFcBXHlTA4VgsjKK1cGrFCo0BPx1FePlJGAJnRzYWHjAB8Pmd4uC/IZ54mStfr9q+zpcTu3zuBNtctrmBfKuUHV+ffST5dCKt83/5KUrlc9Od11CsyyMy1zdRD9QwokWrhHNxSqqlQ+/d3VoULjmjVaEcwh89TlRcpZ9dVjfx02eaqsOnpmmT7ArxQ8sld2175gWojNmXjvXsfnkDDhXdrCESDO0Vv7wvRh0Vt3fy3ffbgluI+PyyXBkSIXT+PjjtRyeglvmiyKN9zt0+ayRm4Vf+0/pWLJsrRmsygIMic2yvTCvbvOBh2D2k7CkxBVbFJTK3R31mcT5iv9JV7WXpZyXKr7pJDQKPlWQ/9NF6QNQTGjyNaIFKf7W+QsCho+F9pdKdpFBK8bZEVZWflLG5ixNQpHxYffMTkxX8ppeHhoHx+njzteeFiFIqe8rUKxp1yxCOQAkCXVfWSLlnQMFbFNvYH4HCUIadUAQi9CYz+z49h7lUL6R477tmvIE8CW+ACYlrAkfW1PlGfhVQHDI4tPih8/B+BSLeO7B9JXheC5dZud54Qim1nA9lKFIC2spzeeLtHdMhyXsaqMU8lILV+nszCrLcQ/uzXf6rYVY9NLaA66qgcz9r0zdG/Y0lwWIcVPdz6e29E=
  bucket: myexquisitewear.com
  local-dir: $TRAVIS_BUILD_DIR/dist
  acl: public_read
  detect_encoding: true
  default_text_charset: 'utf-8'
  cache_control: "max-age=31536000"
  on:
    repo: pekuria/myexquisitewear-app
    branch : master
  skip_cleanup: 'true'
#after_deploy:
#  provider: script
#    - npx semantic-release
